### ISSUE TITLE
Ticker sometimes does odd redraw

### ISSUE THREAD

**Issue by kylebyerly-hp** [HewlettPackard/grommet#144] opened 2015-08-10 19:58 UTC
I haven't quite narrowed this one down. But it does fix itself after a whole 'normal' width worth has been drawn all scrunched up, usually.

It'll scrunch the existing data all to the left, and then start updating far to the right. I don't usually see it on a refresh of the page, usually only when pages other than chart have been loaded. I have only seen it on chrome.

![ticker weirdness](https://cloud.githubusercontent.com/assets/13527666/9182260/fda6061e-3f66-11e5-8eee-5169000c0170.png)

The width of the anomaly isn't always the same...
![ticker weirdness2](https://cloud.githubusercontent.com/assets/13527666/9182352/64d891a8-3f67-11e5-9a28-c2a838835744.png)

**Comment by ericsoderberghp** [comment] 2015-08-26 20:32
This was caused by the Ticker data initializing on app load but the data adjustments only coming once you navigated to the Chart page. This was fixed in 0e0a6b3ac5c9c6bbd696b1256410eed123737d24.

**Closed by ericsoderberghp** 2015-08-26 20:32 UTC
